name: Continuous Integration

on:
  # Trigger the workflow on push or pull request,
  ## but only for the main branch
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build :
    env : 
      NODE_ENV: ${{secrets.NODE_ENV}}
      CMS_API_TOKEN : ${{secrets.CMS_API_TOKEN}} 
      CMS_REVALIDATE_TOKEN: ${{secrets.CMS_REVALIDATE_TOKEN}}
      CI : true

    name : Build the Site
    runs-on : ubuntu-latest
    steps :
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
    # ESLint and Prettier must be in `package.json`
      - name: Install Node.js dependencies
        run: yarn install --frozen-lockfile
        
      - name : Build the Site
        run : yarn build

  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      # ESLint and Prettier must be in `package.json`
      - name: Install Node.js dependencies
        run: yarn install --frozen-lockfile

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          auto_fix: true
          repo-token : ${{ secrets.PR_ACTION }}
          eslint: true
          eslint_args: "--no-error-on-unmatched-pattern"
          eslint_auto_fix: true
          prettier: true
          prettier_auto_fix: true
